### ISSUE TITLE
Doesnot go to absolute bottom on FullScreen/immserive mode. Model mi note 5 pro

### ISSUE THREAD

**Issue by agubha** [amarjain07/StickyScrollView#12]
There is empty white space when full screen mode is turn on in devices like mi note 5 pro, one plus 6 . I haven't tested on other devices but out of 2 mobile with full screen both had the same problem
`https://i.imgur.com/a4iqu3H.jpg`

**Comment by amarjain07** [comment]
Fixed in v1.0.3
