### ISSUE TITLE
Stick the same view

### ISSUE THREAD

**Issue by MoaazElneshawy** [amarjain07/StickyScrollView#22]
I want to make one view is sticky to header and footer,
if it's sticky to footer, it'll be free from header and if it sticky to header, it'll be free from footer,
I tried to use the functions provided by the scrollView but it only sticky to header successfully

	if (binding.scrollView.isViewVisible(binding.countsContainer).not()) {
								binding.scrollView.freeHeader()
								binding.scrollView.freeFooter()
						}
						if (binding.scrollView.isViewVisible(binding.metaDivider)) {
								binding.scrollView.freeFooter()
								binding.scrollView.initHeaderView(binding.countsContainer.id)
						}

**Comment by amarjain07** [comment]
@MoaazElneshawy The same view can either be sticky on top as a header or at the bottom as a footer. It can not stick at both positions simultaneously.
