### ISSUE TITLE
Library dependency is broken 

### ISSUE THREAD

**Issue by imran4u** [amarjain07/StickyScrollView#23]
What went wrong:
Execution failed for task ':saltside-android:mergeIkmanReleaseArtProfile'.
> Could not resolve all files for configuration ':saltside-android:ikmanReleaseRuntimeClasspath'.
   > Could not resolve com.github.amarjain07:StickyScrollView:1.0.2.
     Required by:
         project :saltside-android
      > Could not resolve com.github.amarjain07:StickyScrollView:1.0.2.
         > Could not get resource 'http://dl.bintray.com/populov/maven/com/github/amarjain07/StickyScrollView/1.0.2/StickyScrollView-1.0.2.pom'.
            > Could not GET 'http://dl.bintray.com/populov/maven/com/github/amarjain07/StickyScrollView/1.0.2/StickyScrollView-1.0.2.pom'. Received status code 502 from server: Bad Gateway

**Comment by amarjain07** [comment]
Published 1.0.3
