### ISSUE TITLE
Set stickyFooter and stickyHeader by code

### ISSUE THREAD

**Issue by thanhbinh84** [amarjain07/StickyScrollView#3]
Hi @amarjain07, 

Thanks for creating such a useful library. 

I did check the sample app, it seems we don't support setting stickyFooter and stickyHeader dynamically by code. Do you have any plan adding that features? 

Otherwise, please give me some idea, I will try and create pull request then. 

Thank again.

**Comment by amarjain07** [comment]
Added support in v1.0.3
